input_dim: 2
hidden_dims: [64, 64, 64]
m_dim: 16
lr: 0.001
batch_size: 512
num_epoch: 100
save_dir: "reaction_diffusion_output/"
save_name: "reaction_diffusion_model_random"
load_dir: "reaction_diffusion_output/"
# load_name : None
seed: 315
pre_train: false
nonlinearity: "relu"
iterations: 15
