input_dim: 2
hidden_dims: [64, 64, 64]
m_dim: 16
lr: 0.001
batch_size: 512
num_epoch: 100
save_dir: "reaction_diffusion_output_1_0/"
save_name: "reaction_diffusion_model_pretrained_linear"
load_dir: "reaction_diffusion_output_1_0/"
load_name: "pretrained_model_1_0.pth"
seed: 315
pre_train: false
iterations: 15
